[package]
name = "backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.28"
opendal = "0.43.0"
reqwest = "0.11.22"
tar = "0.4.40"
tokio = { version = "1.35.0", features = ["full"] }
